#
# Copyright 2026 Universidad Complutense de Madrid
#
# This file is part of pypistrello.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# License-Filename: LICENSE
#

line_restframe: 6562.8
line_name: "Halpha"

# General settings for the plots and PDFs saved in the output directory.
general:
  manual_trapz_check: True        # If True, the calculation of trapezoids is also calculated manually (if False, only numpy.trapezoids is used).
  trapz_nbins: 100                # Number of bins for the area calculation using trapezoids in the manual mode.
  plot_residuals: True            # Save plots with the residuals of line-fitting.
  plot_simulated_spectra: False   # Add simulated spectra to the plots if provided.

plotting:
  zoom_plot: [6526.71, 6650.69]   # xmin and xmax for the fitting plots
  y_padding: 0.10                 # fraction to adapt the y-axis depending on the y-values in the plot

  plots_per_page: [4, 2]          # rows, cols
  show_preview: False
  save_pdf: True                              
  pdf_name: "plots_trapz_spectrum.pdf"

# Line-fitting settings
line:
  window_line:
  fit_region: [6574.09, 6586.64]
  line_model_fit: True             
 
# Continuum-fitting settings
continuum:
  window_cont:
  continuum_region: [6530.54, 6643.57]
  excluded_region:
    - [6563.52, 6567.46]
    - [6598.46, 6603.96]
  poly_order_cont: 1

# Crosscorrelation
crosscorr:
  reference_spectrum: [87, 97]      # (x,y) coordinates in FITS format

# Map-plotting
flux_map:
  data_column: "line_flux_trapz"
  colorbar_label: "Flux [erg/s/cm²/A]"
  cmap: "plasma"
  vmin: null
  vmax: null
  wcs_activate: False
  calculate_contours: True
  contour_levels: 10
  interpolate: False
  interpolation_method: "nearest"   # nearest, linear, cubic

velocity_map:
  data_column: "velocity"
  colorbar_label: "Velocity [km/s]"
  cmap: "seismic"
  vmin: -100
  vmax: 100
  wcs_activate: False
  add_flux_contours: False
  contours_color: "black"
  interpolate: False
  interpolation_method: "nearest"   # nearest, linear, cubic